name: Android Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x android-app/gradlew
      
    - name: Clean project
      working-directory: android-app
      run: ./gradlew clean --no-daemon
      
    - name: Check Gradle configuration
      working-directory: android-app
      run: ./gradlew tasks --no-daemon
      
    - name: Build Debug APK
      working-directory: android-app
      run: ./gradlew assembleDebug --no-daemon --no-build-cache --stacktrace
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2
        
    - name: Upload Debug APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android-app/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Build Release APK
      working-directory: android-app
      run: ./gradlew assembleRelease --no-daemon --no-build-cache --stacktrace
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2
        KEYSTORE_PASSWORD: android
        KEY_ALIAS: androiddebugkey
        KEY_PASSWORD: android
        
    - name: Upload Release APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: android-app/app/build/outputs/apk/release/app-release.apk
        retention-days: 30
